---
- name: Create folders for Grafana container config files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
  loop:
    - grafana/postgres
    - grafana/data
- name: Copy Grafana environment files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
  loop:
    - grafana-postgres.env
    - grafana.env
- name: Create Grafana secret for database password
  containers.podman.podman_secret:
    state: present
    name: grafana_db_passwd
    data: "{{ grafana_db_passwd }}"
  become: true
  become_user: "{{ podman_user }}"
- name: Change owner of grafana/data directories to podman_user_id:podman_group_id
  # We need to run Grafana as podman user inside Grafana container
  # Podman is unable to automatically change the owner of directories inside containers
  # so we need to user podman unshare to run chown inside Podman's user namespace
  ansible.builtin.shell: |
    podman unshare chown -R {{ podman_user_id }}:{{ podman_group_id }} {{ podman_appdata_dir }}/grafana/data
  become: true
  become_user: "{{ podman_user }}"
- name: Create grafana-postgres quadlet
  containers.podman.podman_container:
    name: grafana-postgres
    image: docker.io/postgres:16.11@sha256:6c7be86be8db1d8f6bddf1847a0e9c690fa313d141a41665b0b804a3de737c09
    state: quadlet
    quadlet_filename: grafana-postgres
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: monitoring.pod
    volumes:
      - "{{ podman_appdata_dir }}/grafana/postgres:/var/lib/postgresql/data:Z"
    env_file:
      - grafana-postgres.env
    secrets:
      - grafana_db_passwd
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Create Grafana quadlet
  containers.podman.podman_container:
    name: grafana
    image: docker.io/grafana/grafana:12.2@sha256:35c41e0fd0295f5d0ee5db7e780cf33506abfaf47686196f825364889dee878b
    state: quadlet
    quadlet_filename: grafana
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: monitoring.pod
    user: "{{ podman_user_id }}"
    volumes:
      - "{{ podman_appdata_dir }}/grafana/data:/var/lib/grafana:Z"
    env:
      GF_INSTALL_PLUGINS: "grafana-clock-panel"
    env_file:
      - grafana.env
    cap_drop:
      - all
    secrets:
      - grafana_db_passwd
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Unit]
        Requires=grafana-postgres.service
        After=grafana-postgres.service
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Grafana
  ansible.posix.firewalld:
    port: "3000/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
