- name: Create folder for Speedtest-tracker config files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/speedtest-tracker/config"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Copy Speedtest-tracker environment files
  ansible.builtin.copy:
    src: "speedtest-tracker.env"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Create Speedtest-tracker Quadlet
  containers.podman.podman_container:
    name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:1.7.1@sha256:f09edeb0c1dbb63db9c0bf256e8cb41cea48943d97881dba4522991051ebd28c
    state: quadlet
    quadlet_filename: speedtest-tracker
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "8080:80"
    volumes:
      - "{{ podman_appdata_dir }}/speedtest-tracker/config:/config:Z"
    env_file:
      - speedtest-tracker.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Speedtest-tracker
  ansible.posix.firewalld:
    port: "8080/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
