---
- name: Set service name variable
  ansible.builtin.set_fact:
    service_name: uptime-kuma
- name: Create folder for Uptime Kuma data files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/uptime-kuma/data"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Create uptime-kuma quadlet
  containers.podman.podman_container:
    name: uptime-kuma
    image: docker.io/louislam/uptime-kuma:2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    state: quadlet
    quadlet_filename: uptime-kuma
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "3001:3001"
    volumes:
      - "{{ podman_appdata_dir }}/uptime-kuma/data:/app/data:Z"
    cap_add:
      - NET_RAW
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Uptime Kuma
  ansible.posix.firewalld:
    port: "3001/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
