---
- name: Set service name variable
  ansible.builtin.set_fact:
    service_name: actual-budget
- name: Create folders for Actual Budget data files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/actual-budget/data"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0750"
- name: Create Actual Buget Quadlet
  containers.podman.podman_container:
    name: actual-budget
    image: docker.io/actualbudget/actual-server:25.12.0@sha256:7f38b450cc3b7523dd5377792895e58b9cf333769e5a27f89e643b6f5fc60565
    state: quadlet
    quadlet_filename: actual-budget
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "5006:5006"
    volumes:
      - "{{ podman_appdata_dir }}/actual-budget/data:/data:Z"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Actual Budget
  ansible.posix.firewalld:
    port: "5006/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
