---
- name: Set service name variable
  ansible.builtin.set_fact:
    service_name: changedetection
- name: Create folder for Changedetection data
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/changedetection/datastore"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Copy Changedetection environment files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
  loop:
    - changedetection.env
    - chromium-playwright.env
- name: Create changedetection pod
  containers.podman.podman_pod:
    name: changedetection
    state: quadlet
    quadlet_filename: changedetection
    quadlet_dir: "{{ quadlet_dir }}"
    infra_name: "changedetection-pod"
    ports:
      - "5000:5000"
- name: Create chromium-playwright Quadlet
  containers.podman.podman_container:
    name: chromium-playwright
    image: ghcr.io/browserless/chromium:v2.38.2@sha256:d5583d92f135c541667fca63bc7210cf51122c1317335374aa64b191fbaa0ef2
    state: quadlet
    quadlet_filename: chromium-playwright
    quadlet_dir: "{{ quadlet_dir }}"
    pod: changedetection.pod
    env_file:
      - chromium-playwright.env
    shm_size: "2gb"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Restart service
- name: Create changedetection Quadlet
  containers.podman.podman_container:
    name: changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.50.40@sha256:a3684335bc4806b305b40271abc787687e716fbf68bfdb8e7e069ee19c599670
    state: quadlet
    quadlet_filename: changedetection
    quadlet_dir: "{{ quadlet_dir }}"
    pod: changedetection.pod
    volumes:
      - "{{ podman_appdata_dir }}/changedetection/datastore:/datastore:Z"
    env_file:
      - changedetection.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Unit]
        Requires=chromium-playwright.service
        After=chromium-playwright.service
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Restart service
- name: Open firewalld port for Changedetection
  ansible.posix.firewalld:
    port: "5000/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
