---
- name: Create folder for FreshRSS data
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/freshrss/data"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
- name: Copy FreshRSS environment file
  ansible.builtin.copy:
    src: freshrss.env
    dest: "{{ quadlet_dir }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Create FreshRSS Quadlet
  containers.podman.podman_container:
    name: freshrss
    image: docker.io/freshrss/freshrss:1.28.0@sha256:5664f42e37e7101c824806d8f73cbc97c8f406ce043bbdb8d39d4ff1e7f2ad11
    state: quadlet
    quadlet_filename: freshrss
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "8089:80"
    volumes:
      - "{{ podman_appdata_dir }}/freshrss/data:/var/www/FreshRSS/data:Z"
    env_file:
      - freshrss.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for FreshRSS
  ansible.posix.firewalld:
    port: "8089/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
