---
- name: Set service name variable
  ansible.builtin.set_fact:
    service_name: librechat-pod
- name: Create folders for Librechat config and data files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
  loop:
    - librechat/config
    - librechat/logs
    - librechat/mongodb/data
    - librechat/meilisearch/data
- name: Change logs folder permissions to 777
  # See https://github.com/danny-avila/LibreChat/discussions/2141#discussioncomment-8845459
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/librechat/logs"
    mode: "1777"
- name: Create Librechat pod
  containers.podman.podman_pod:
    name: librechat
    state: quadlet
    quadlet_filename: librechat
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    infra_name: "librechat-pod"
    ports:
      - "3080:3080"
- name: Generate librechat.env from template
  ansible.builtin.template:
    src: "{{ librechat_env_template_file }}"
    dest: "{{ quadlet_dir }}/librechat.env"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Generate librechat.yaml from template
  ansible.builtin.template:
    src: "{{ librechat_yaml_template_file }}"
    dest: "{{ podman_appdata_dir }}/librechat/config/librechat.yaml"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0644"
- name: Create LibreChat Quadlet
  containers.podman.podman_container:
    name: librechat
    image: ghcr.io/danny-avila/librechat:v0.8.0@sha256:adcb326f43a971b53df0fbca5f4769c8e56fafbdf834c9dd8c7e4924788f0152
    state: quadlet
    quadlet_filename: librechat
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    volumes:
      - "{{ podman_appdata_dir }}/librechat/config/librechat.yaml:/app/librechat.yaml:Z,ro"
      - "{{ podman_appdata_dir }}/librechat/logs:/app/api/logs:Z"
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Restart service
- name: Create LibreChat-mongodb Quadlet
  containers.podman.podman_container:
    name: librechat-mongodb
    image: docker.io/mongo:8.0.15@sha256:f4d54619262ae3bc6a0a8efbebcef970b87b8ad70697479a75ce308a6f400158
    state: quadlet
    quadlet_filename: librechat-mongodb
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    volumes:
      - "{{ podman_appdata_dir }}/librechat/mongodb/data:/data/db:Z"
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Restart service
- name: Create LibreChat-meilisearch Quadlet
  containers.podman.podman_container:
    name: librechat-meilisearch
    image: docker.io/getmeili/meilisearch:v1.12.3@sha256:4acfcbbb9e089aa1aac838cfda3fba7f07aaaef044c23da8acbe0ab741400dac
    state: quadlet
    quadlet_filename: librechat-meilisearch
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    pod: librechat.pod
    volumes:
      - "{{ podman_appdata_dir }}/librechat/meilisearch/data:/meili_data:Z"
    env_file:
      - librechat.env
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Restart service
- name: Open firewalld port for Librechat
  ansible.posix.firewalld:
    port: "3080/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
