---
- name: Set service name variable
  ansible.builtin.set_fact:
    service_name: readeck
- name: Create folders for Readeck data files
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/readeck/data"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0750"
- name: Create readeck Quadlet
  containers.podman.podman_container:
    name: readeck
    image: codeberg.org/readeck/readeck:0.21.2@sha256:f1122d768294231a99a34c12055fa495404e91d138b2cf7ce619c2bc4de0fffe
    state: quadlet
    quadlet_filename: readeck
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "8000:8000"
    volumes:
      - "{{ podman_appdata_dir }}/readeck/data:/readeck:Z"
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Restart service
- name: Open firewalld port for Readeck
  ansible.posix.firewalld:
    port: "8000/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
