---
- name: Set service name variable
  ansible.builtin.set_fact:
    service_name: stirling-pdf
- name: Create folder for Stirling-PDF logs
  ansible.builtin.file:
    path: "{{ podman_appdata_dir }}/{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
  loop:
    - stirling-pdf/logs
    - stirling-pdf/extraConfigs
- name: Generate stirling-pdf.env from template
  ansible.builtin.template:
    src: "{{ stirling_pdf_env_template_file }}"
    dest: "{{ quadlet_dir }}/stirling-pdf.env"
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0600"
- name: Create Stirling-PDF Quadlet
  containers.podman.podman_container:
    name: stirling-pdf
    image: ghcr.io/stirling-tools/s-pdf:2.1.0@sha256:56dd735b7b59ca4fe69266f6f1933cd4e1c203ac46f0886845c4d5fc1bc65cf1
    state: quadlet
    quadlet_filename: stirling-pdf
    quadlet_file_mode: "0644"
    quadlet_dir: "{{ quadlet_dir }}"
    ports:
      - "8080:8080"
    volumes:
      - "{{ podman_appdata_dir }}/stirling-pdf/logs:/logs:Z"
      - "{{ podman_appdata_dir }}/stirling-pdf/extraConfigs:/configs:Z"
    env_file:
      - stirling-pdf.env
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - FOWNER
      - SETUID
      - SETGID
    quadlet_options:
      - "NoNewPrivileges=true"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=default.target
- name: Open firewalld port for Stirling-PDF
  ansible.posix.firewalld:
    port: "8080/tcp"
    permanent: true
    immediate: true
    state: enabled
  notify:
    - Reload firewalld
