---
- name: Reload firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: "reloaded"
    enabled: true

- name: Restart service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: "restarted"
    scope: "user"
    daemon_reload: true
    enabled: true
  become: true
  become_user: "{{ podman_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ __user_info.uid }}"
