---
- name: Install Tailscale
  hosts: pbs,services_srv,monitoring_srv,infisical_srv
  roles:
    - role: artis3n.tailscale.machine
      vars:
        tailscale_authkey: "{{ lookup('ansible.builtin.env', 'TAILSCALE_KEY') }}"
